### ISSUE TITLE
민감한 DB접속 정보를 숨기시는것을 추천드립니다

### ISSUE THREAD

**Issue by fnrkp089** [Camof1ow/toyproject#5]
flask에 환경변수를 만들어 DB접속정보를 숨기시는것을 정말 추천드립니다
해당되는 주소는 붙여넣고 연결하는 순간 모든 정보를 누구나 확인할수있고 누구나 삭제할수있습니다

**Comment by Camof1ow** [comment]
좋은 정보 남겨주셔서 감사합니다!!
